ITSERVICES:
  - ZOOKEEPER:
      image: stratio/zookeeper:3.4.6

  - KAFKA:
      image: stratio/kafka:0.8.2.1
      env:
        - ZOOKEEPER_HOSTS=%%ZOOKEEPER:2181

ITPARAMETERS: >
      -Dzookeeper.hosts=%%ZOOKEEPER:2181
      -Dkafka.hosts=%%KAFKA:9092